### ISSUE TITLE
Bug: Duplicate conversations visible in list

### ISSUE THREAD

**Issue by elisealix22** [xmtp-labs/xmtp-inbox-ios#42]
We'd like to dedupe conversations based on peerAddress. Right now I believe they are unique because they have unique topics.

![IMG_0008](https://user-images.githubusercontent.com/556051/216382268-4f974ae1-4631-4c70-b8f6-62ea31abc81e.jpg)

**Comment by nakajima** [comment]
I wonder if this makes sense to add to the SDK? It feels like something more people could run into? Maybe adding something like a `ConversationGroup` that has a peer address then a list of topics and sorts all messages from those topics by date?

**Comment by nakajima** [comment]
This should be fixed up now.
